name = "icon-collection-web"
compatibility_date = "2026-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "icon-collection"
database_id = ""

[[r2_buckets]]
binding = "ICONS"
bucket_name = "icon-collection"
